### ISSUE TITLE
Kernel panic - not syncing: BIOS has enabled x2apic but kernel doesn't

### ISSUE THREAD

**Issue by srinivasluv** [01org/luv-yocto#83] opened 2016-05-16 08:54 UTC
Dear LUV Team,

Really liked the LUV, as I went through its capabilities.. It Is really a cool stuff.

I tried to boot LUV on one of a blade in our blade server, and attached is the results of the same.

I have following questions : 
1)  I Get “Kernel panic - not syncing: BIOS has enabled x2apic but kernel doesn't support x2apic, please disable x2apic in BIOS” Message, But BIOS that we use does not allow us to explicitly disable x2apic, so in this case how do I go about running LUV ?
2)  I tried to boot LUV from UEFI Shell using “bootx64.efi” but I did not see any graphics or progress bar like as u show in Documentation demo video, is this expected?
3)  Also the output shows several MSR tests, could you educate me about how to interpret these logs to determine PASS/FAIL?

Could you help me with this..

Thanks in advance 

Srinivas BN

**Comment by ricardon** [comment] 2016-05-17 14:19
Hi Srinivas,

Thanks for trying LUV. I am glad you liked it. Unfortnately, I am unable to find the attached results to mention. Were they attached at all?

Regarding your questions, here are my comments.

1. Actually, we have seen similar errors related to x2apic. I guess that you mentioning this issue would merit to include x2apic in the kernel configuration. I think this can be included as part of our upcoming release this week. I will keep you posted.

2. The fact that you don't see any graphics of progress bar makes me think that there was an error while booting. Perhaps this is related to the issue 1) about the kernel not syncing and, therefore, not reaching the user space.

3. I guess that you are referring to the MSR tests that BITS perform. Maybe you could reattach the results to take a look.

Thanks and BR,
Ricardo

**Comment by srinivasluv** [comment] 2016-05-20 04:08
HI Ricardo,

Greetings ! 
Thanks for the clarification!

For 1 & 2 . I will stay tuned for new release and try out. 

For 3. Attached are the logs. Please take a look..

Best Regards,
Srinivas
[LUV_NH.txt](https://github.com/01org/luv-yocto/files/273859/LUV_NH.txt)
[LUV_DH.txt](https://github.com/01org/luv-yocto/files/273860/LUV_DH.txt)

**Comment by srinivasluv** [comment] 2016-07-08 04:27
Hi Ricardo,

Any update on this?

Best Regards,
Srinivas

**Comment by ricardon** [comment] 2016-07-12 01:54
Hi Srinivas,

I apologize for the long delay in replying. Here are a few comments:

*In LUV_NH and LUV_DH you have several test cases failed because some MSR (addresses 0xHHH) are not consisten across CPUs. It may be the case that this is expected because BITS caters for a blacklist of CPUs for which consistency is not expected. Thus, it may be that either the blacklist needs to be updated for your system or there is a legitimate consistency problem. Does this ring a bell? Perhaps if you have a list of MSRs for which you expect inconsistency we could look at add it to this black list.

*I also saw that BITS failed in LUV_DH.txt to recognize X2APIC entries in the ACPI tables. I don't think BITS supports that at the moment.

*Lastly, we have released LUV v2.1-rc1, which has support for X2APIC. Maybe you could try to give it a try. It has the same version of BITS, though.

I will try to collect snippets of the BITS source code so that you have better insight on what it is being tested.

Thanks and BR,
Ricardo

**Comment by ricardon** [comment] 2016-07-12 15:30
By the way, you can look at the release note here:

https://lists.01.org/pipermail/luv/2016-June/001211.html

along with information on how to retrieve the latest binaries.

Thanks!

**Comment by srinivasluv** [comment] 2016-08-12 07:26
Hi Ricardo,

Thanks a lot for forwarding the download link to new Build. I Could Boot the image "luv-live-2.1-rc1_diskboot_x86_64.img" successfully on my server. I didn't see xAPIC Kernel panic issue.
I Booted and run "luv-live-2.1-rc1_diskboot_x86_64.img" from the UEFI Shell

Thanks !

Srinivas BN

**Comment by srinivasluv** [comment] 2016-08-12 07:34
Hi Ricardo,

I Encountered different issue now with LUV. Attached are the screen shot and Serial debug logs when the LUV tool halted to boot. The message from LUV reads "STOP ! No partition found to store the results.. please report to luv@lists.01.org". But I have a Sandisk USB Thumb Drive of size 8GB . 

Could you please guide me? LEt me know if you would need any other inputs


![luv stoped sdx](https://cloud.githubusercontent.com/assets/19385491/17615628/2156eb76-608d-11e6-8a78-77eb4d2886b2.PNG)

[LUV.txt](https://github.com/01org/luv-yocto/files/414782/LUV.txt)

Thanks in Advance !

Best Regards,
Srinivas B.N


 or logs from me.

**Comment by ricardon** [comment] 2016-08-13 23:36
Hi Srinivas,

This happens when because, well, LUV cannot find the disk partition it uses to save the test results. The LUV disk has two partitions. 1) the results partition and 2) the boot partition. LUV finds the partitions using the information in the /dev/disk/by-uuid directory. I suggest you to try the following things:

1. How are you flashing your USB thumb disk? Did you follow the methods detailed here: https://01.org/linux-uefi-validation/documentation/flashing-your-usb-stick?

2. If the method in 1. does not solve your problem, some debugging will be needed. Can you insert your LUV stick in any other Linux machine and do the following:

`linux-system$ sudo  fdisk /dev/sdX`

where sdX is your LUV USB thumb disk.

Once in fdisk, you can use the 'p' command and you should see two partitions as follows:
```

Command (m for help): p

Disk /dev/sdX: 129 MB, 129024512 bytes
255 heads, 63 sectors/track, 15 cylinders, total 252001 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000c61f9
```

```
               Device Boot      Start         End      Blocks   Id  System
luv-live-image64.img1               1       32768       16384    c  W95 FAT32 (LBA)
luv-live-image64.img2   *       32769      252000      109616    c  W95 FAT32 (LBA)
```

3) In the boot partition of your LUV USB thumb disk open the file /EFI/BOOT/grub.cfg and at the end of the linux line, add "noluv" so that it looks like:

`linux /vmlinuz ${SYSLINUX_ROOT} debug crashkernel=256M console=ttyS0,115200 console=ttyPCH0,115200 ip=dhcp log_buf_len=1M luv_netconsole=10.11.12.13,64001 **noluv**`

Try to boot LUV again and eventually you will get to a login screen. Log as root and no password and list the contents of the directory /dev/disk/by-uuid:

```
root@qemux86-64$ ls /dev/disk/by-uuid
05D6-1523 423c-C2C8
```

The partition we are looking for is 05D6-1523. If you don't see it after following 1) and 2) then it could mean that we are missing a driver for your server.

**Comment by srinivasluv** [comment] 2016-08-16 10:36
Hi Ricardo,

Thanks for the debug information. Looks like the drivers did not get copied correctly. while flashing the USB pendrive from my windows laptop.. I re flashed LUV using Linux system and it works now.

![luv](https://cloud.githubusercontent.com/assets/19385491/17696259/e4af55fa-63ca-11e6-9bac-48eda3a8b833.PNG)

Attached is the results that the Pen drive had ...

[Results.zip](https://github.com/01org/luv-yocto/files/420019/Results.zip)

Thanks

**Comment by ricardon** [comment] 2016-08-19 20:48
Great news! Do the results look OK to you? Do you have comments or questions?

**Comment by ricardon** [comment] 2017-07-13 19:00
@prakhya was able to reproduce and fix this issue. You should not see it in our latest release images. I am closing this issue for now. If you encounter it again, please feel free to re-open it.

**Closed** 2017-07-13 19:00 UTC
