### ISSUE TITLE
CHIPSEC tests cause hang on ASUS P8H67-M LE

### ISSUE THREAD

**Issue by mfleming** [01org/luv-yocto#7] opened 2014-06-09 11:51 UTC
Running the chipsec tests on my ASUS P8H67-M LE to hang. This is the reason behind commit https://github.com/01org/luv-yocto/commit/af66ed38bad4337c1a639a8932733b2e7eddea12.

Quoting from the commit message,

```
 The fact that the tests cause lockup isn't the biggest problem, it's
 that there's absolutely zero diagnostic information provided to the
 user, so they've no data to report other than "my machine freezes".
```

What we need is a way of diagnosing this hang and collecting useful information.

Labeling this as both an enhancement and a bug because we need to add the diagnostic features (enhancement) to figure out whether the lockup is incorrectly caused by CHIPSEC (bug) or caused due to an issue with the firmware.

**Comment by meghadey** [comment] 2017-10-18 23:28
closing since we do not have access to the system. We have pstore enabled now. If this was caused by a panic, this should be flushed to the pstore efi backend.

Can be reopened if issue still exists.

**Closed by meghadey** 2017-10-18 23:28 UTC
Labels: bug, feature
